version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/boxes/blog"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/boxes/cv"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/boxes/garden"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/car"
    schedule:
      interval: "monthly"
